//! Framework-neutral diagnostic events.
//!
//! The library does not depend on `log` or `tracing`. An application can bridge
//! these events to either ecosystem by implementing [`Reporter`] locally.

/// Logging severity chosen by the library.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Level {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
}

/// A stable category that lets reporters format or filter events themselves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventKind {
    LoadStarted,
    LoadFinished,
    DotenvLoaded,
    VariableLookup,
    VariableResolved,
    ComputationStarted,
    ComputationFinished,
    MaterializationStarted,
    MaterializationFinished,
    Issue,
}

/// A borrowed structured event.
///
/// Values are never part of an event. Only names, source information and a
/// sanitized description are exposed.
#[derive(Debug, Clone, Copy)]
pub struct Event<'a> {
    pub level: Level,
    pub kind: EventKind,
    pub field: Option<&'a str>,
    pub key: Option<&'a str>,
    pub source: Option<&'a str>,
    pub message: &'a str,
}

/// Receives diagnostic events generated by the loader.
pub trait Reporter: Send + Sync + 'static {
    fn report(&self, event: &Event<'_>);
}

/// Closures can be used as reporters without declaring a separate type.
impl<F> Reporter for F
where
    F: for<'a> Fn(&Event<'a>) + Send + Sync + 'static,
{
    fn report(&self, event: &Event<'_>) {
        self(event);
    }
}

/// Default reporter used when the application does not request diagnostics.
#[derive(Debug, Default)]
pub(crate) struct NoopReporter;

impl Reporter for NoopReporter {
    fn report(&self, _event: &Event<'_>) {}
}

